### ISSUE TITLE
[feature request] Support for Feed The Beast servers

### ISSUE THREAD

**Issue by cornuwel** [hexparrot/mineos#102]
This would require two steps, first one is simple: provide stock profiles for the different modpacks. Second one requires to run the FTBInstall.sh script (which downloads the relevant vanilla server jarfile) after unpacking the zipfile.

I'll have a look into this and make a pull request if I manage to make it work.

Regards,

**Comment by hexparrot** [comment]
One reason why FTB doesn't already have stock profiles is because it appears there is no standard in how the server is started (or at least, which script it includes).  For example, consider the following modpack contents:

Feed The Beast Beta Pack A:
FTB-Beta-A.jar
Server Start 1GB.bat
Server Start 2GB.bat
....
Server Start 10GB.bat

Tech World:
ftbserver.jar
ServerStart.bat
ServerStart.sh

Direwolf20:

FTBInstall.sh
FTBInstall.bat
FTBServer-1.7.10-1272
ServerStart.sh
ServerStart.bat

I would love to be able to include more functionality for these server packs, but there does not appear to be any standardization that I can depend on, in terms of the jar filenames, the recommended jar arguments, and pre-running scripts.

And that doesn't even address the fact that the URLs look like this:

modpacks^direwolf20_17^1_0_3^direwolf20_17-server.zip

^ (carets) are ridiculous URL characters and force me to remove sanitization.

If they can come up with a system that can be relied on to always successfully start up a server from a systematic perspective, I'd be happy to design a way for it to work (or accept a PR).  However, I am cautiously pessimistic there will be a clean way to do this without hardcoding in each step of the way on a per-pack basis.

Ultimately, I'd see the best solution as creating a new profile type that would extract the files, identify script X (hopefully is *always* FTBInstall.sh) and then run a server jar that is always named ftbserver.jar (and not FTBServer-1.7.10-1272).  

Only then will I even worry further about the influx of help requests asking why it doesn't regard the "MaxPermGenSize" and other java arguments that the ServerStart.sh include.

**Comment by hexparrot** [comment]
Fact:  If all Feed the beasts could use a standard like:

./install.sh
./start.sh
with a constant jar filename like ftbserver.jar

Then every FTB pack would have a stock profile....like tomorrow.

**Comment by cornuwel** [comment]
Sorry for the late reply. 

Maybe just adding options to the profile for a runOnce script and a startup script? The jarfile name is already there. That would allow to create profiles for the different variants.

**Comment by hexparrot** [comment]
MineOS (Python iteration) is pretty much unchanging, as far as the code-base is concerned.  There's just too many people with production environments and too few willing to run development branches to test new code changes.

In short, it seems that hexparrot/mineos won't be updated to accommodate this functionality, but hexparrot/mineos-node (the nodejs based iteration) already does.  It's nearly ready, but at this point just needs testing help from the community.
