### ISSUE TITLE
Subdirectory Support

### ISSUE THREAD

**Issue by 416C616E** [hexparrot/mineos#103]
You have a lot of static references within your program, not allowing for the ability to mod_proxy the MineOS panel to a domains subdirectory. Through a lot of find & replace I managed to get it working, but native support for it would be nice.

**Comment by hexparrot** [comment]
It could help push things along for me if you could provide me with some of the specific changes you've made that made it work (and what specifically you were configuring for subdomains).   I've done my best to try to keep paths relative to the current directory where possible, and only a few places can I think of deviations, e.g., "/auth/login" and other paths that are virtual paths rather than real ones.

'diff' is actually a nice utility that could provide your changes to me in a clean, systematic way (in case you're not altogether too familiar with git and pull requests).

Most of my development efforts recently have been directed toward the new web-ui using Nodejs, so anything you can help save me effort with (showing me your working adjustments) can make this more expedient.

**Comment by 416C616E** [comment]
I made changes to server.py, auth.py, login_en.html and index_en.html. Most of these changes were just adjusting urls to be appropriate to my subdirectory, still hardcoded, but fixed to where I needed it. IE, "/" being changes to "/MineOS/".
