### ISSUE TITLE
start.sh script :( 

### ISSUE THREAD

**Issue by cnniillaa** [hexparrot/mineos#104]
Hello I cannot get my start.sh script working for a plugin called goldrush what happens is after the game is over the server restarts but all the scripts I have tried are not working this is my current

#!/bin/bash
waitandrun(){
echo waitandrun start >> /var/games/minecraft/servers/goldrush//starts.log
sleep 300
setsid ./mineos_console.py -s goldrush/ start >> /var/games/minecraft/servers/goldrush//starts.log 2>&1
echo waitandrun end >> /var/games/minecraft/servers/goldrush//starts.log
}
date >> /var/games/minecraft/servers/goldrush/starts.log
cd /usr/games/minecraft
waitandrun &
echo end of start.sh >> /var/games/minecraft/servers/goldrush//starts.log

**Comment by Siliconheart** [comment]
Hi.
1. Are you sure your server restarts, and not just stop? Is there line 'Restarting server...' in the last lines of /logs/latest.log? Or maybe 'Stopping server'?
2. I used separate script files, not just function in my working setup - this can be the issue, because script that runs server must be detached from screen session (and, more important, from java session - because it kills all its children on server stop) by setsid and &. 
3. Check your starts.log to find out which step is last run.
4. Remove extra / before starts.log and between goldrush and start
5. Remember there is 5 minutes (300 seconds) timeout before server starts.

Try this two files:
start.sh:
```shell
#!/bin/bash
date >> /var/games/minecraft/servers/goldrush/starts.log
setsid ./waitandrun.sh &  >> /var/games/minecraft/servers/goldrush/starts.log
echo end of start.sh >> /var/games/minecraft/servers/goldrush/starts.log
```
waitandrun.sh:
```shell
#!/bin/bash
echo waitandrun start >> /var/games/minecraft/servers/goldrush/starts.log
sleep 300
cd /usr/games/minecraft
./mineos_console.py -s goldrush start >> /var/games/minecraft/servers/goldrush/starts.log 2>&1
echo waitandrun end >> /var/games/minecraft/servers/goldrush/starts.log
date >> /var/games/minecraft/servers/goldrush/starts.log
```
Don't forget to 
```shell
chmod a+x *.sh
```
And as root
```shell
chmod a+x /usr/games/minecraft/mineos_console.py
```
(just if you haven't done this after install)

**Comment by cnniillaa** [comment]
OK i did that script and now this is what Im getting

[17:47:43] [Server thread/INFO]: Stopping server
[17:47:42] [Server thread/INFO]: rc2827 lost connection: Server is restarting
[17:47:42] [Server thread/INFO]: Sirr_Mase lost connection: Server is restarting
[17:47:42] [Server thread/INFO]: Sirrr_Stong lost connection: Server is restarting
[17:47:42] [Server thread/INFO]: Window_Licker1 lost connection: Server is restarting
[17:47:42] [Server thread/INFO]: Sirrr_Slime lost connection: Server is restarting
[17:47:42] [Server thread/INFO]: FritzCraftGaming lost connection: Server is restarting
[17:47:42] [Server thread/INFO]: Attempting to restart with ./start.sh

**Comment by Siliconheart** [comment]
1. That's good sign, server is trying to restart. 
2. Post your /var/games/minecraft/servers/goldrush/starts.log to debug further. 
3. Are you sure you have 2 scrips (start.sh and waitandrun.sh)? Post your `ls -l`
4. Maybe it starts after 5 minutes? Decrease timeout in waitandrun.sh from 300 to 30 if your server stops faster (less than 30 seconds)

**Comment by cnniillaa** [comment]
This is my starts.log

end of start.sh
end of start.sh
end of start.sh

Start.sh

#!/bin/bash
date >> /var/games/minecraft/servers/goldrush/starts.log
setsid ./waitandrun.sh &  >> /var/games/minecraft/servers/goldrush/starts.log
echo end of start.sh >> /var/games/minecraft/servers/goldrush/starts.log

waitandrun.sh

#!/bin/bash
echo waitandrun start >> /var/games/minecraft/servers/goldrush/starts.log
sleep 30
cd /usr/games/minecraft
./mineos_console.py -s goldrush start >> /var/games/minecraft/servers/goldrush/starts.log 2>&1
echo waitandrun end >> /var/games/minecraft/servers/goldrush/starts.log
date >> /var/games/minecraft/servers/goldrush/starts.log

**Comment by Siliconheart** [comment]
Looks like you need to run `chmod a+x *.sh` in your server dir, or set 'executable' attribute on waitandrun.sh somehow else.

**Comment by cnniillaa** [comment]
ok how do I do 

chmod a+x *.sh

**Comment by Siliconheart** [comment]
Try this:
1. In browser open https://[your-server-IP]:12320 to open Shell in a box
2. Log in with 'mc' and password
3. Type `chmod a+x /var/games/minecraft/servers/goldrush/*.sh` and press Enter
4. Type `exit` and press enter to leave Shell in a box

You can run commands starting from step 2 from any command-line interface of your server, like using SSH (PuTTY, etc), directly from console of server (if it's a bare-metal Linux box with monitor and keyboard), Webmin->Tools->Command shell (port 12321, root only) and so on.

**Comment by hexparrot** [comment]
For future questions, since this is really about your own script and not about the existing MineOS scripts, you might consider posting it on discourse.codeemo.com, the support forum, as there would be a much larger audience who can help field scripting questions, provide their own experience and maybe even their own homegrown scripts.
