### ISSUE TITLE
webui login: password is visible by default

### ISSUE THREAD

**Issue by kaimi** [hexparrot/mineos#20]
The password field on the login page has visible text by default. It should be _in_visible by default and require user action to show.

**Comment by Eforen** [comment]
I would just like to state my opinion that I agree that signup forms should have passwords visible from a usability standpoint. 

How ever I agree with your links @hexparrot 

smashingmagazine (ux perspective) http://uxdesign.smashingmagazine.com/2012/10/26/password-masking-hurt-signup-form/

trend micro (security perspective)
http://blog.trendmicro.com/trendlabs-security-intelligence/to-or-not-to-mask-usability-versus-security-in-password-masking/

Which both say that login frields should not default to showing their passwords.
smashingmagazine even goes so far as to provide this handy image.

![Do not show login passwords](https://media-mejadiatemple.netdna-ssl.com/wp-content/uploads/2012/10/masking-bad-signups-500.png)

Which shows how they feel about login passwords being hidden by default with a huge green check mark. They don't even have an option to show it.

** Now for my personal user experiance **
I am sorry if any of this sounds like I am attacking you. I would like to assure you that I in no way mean to do so. I hope you are big enough to allow your mind to be changed on this matter because I think it is hurting because I honestly think that staying firm on this issue will do more harm then good. I for one before I realised that it was just HTML and could just reprogram it my self was considering other options after this one prompted me to enter my password and exposed half of my password to someone who should not know the full password access this. I am just glad that I am paranoid enough to use a different password for this software as it would have been very bad otherwise and I would have very different words for you. Please consider other people in a similar situation. This has the potential to make people very very mad! Where as a default option of hidden with a way to expose it shows concern for the users safety and if the would like it default then they can set it as the default in a config. Those that want it exposed by default will be happy that you have a feature normally not available and those that want it hidden by default (the internet standard) will not get mad at you.

It is simple math

mad + happy = not good UX Design
happy + happy + good UX Design

People expect what they see everywhere else and it is almost total impulse to put a username and password in for most people.
