### ISSUE TITLE
[Feature Request] Make backups prunable via.step and date

### ISSUE THREAD

**Issue by TheDoctorsLife** [hexparrot/mineos#93]
I am making this request because it would be a lot easier for backups to be removed via. the sept # So if I wanted to say remove all backup steps, older than 5b then I can remove all backups older than 5B. This is more of a convenience thing than anything else.

**Comment by hexparrot** [comment]
I'm not making many drastic changes to the mineos codebase nowadays since I've pretty much moved all my development efforts into the new upcoming mineos-node.   For the most part, I absolutely agree with the usefulness of 5B rather than a specific date (although my original thinking was to the opposite--for liability concerns), so I'll likely implement this in the next edition (unless somebody else writes it and makes a pull request).

**Comment by TheDoctorsLife** [comment]
Mineos-node sounds interesting, any chance at more info at this time?

**Comment by kalvindukes** [comment]
Yes, please! :)

**Comment by hexparrot** [comment]
I'd be happy to share the progress of the new web-ui, though github (or at least this repo) is not the appropriate place to do it.  The project is https://github.com/hexparrot/mineos-node, but if you want more details (that also can get more exposure), drop a line in discourse.codeemo.com and I can provide pictures, greater detail, etc.
